services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-iptv}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-iptv}
      POSTGRES_DB: ${POSTGRES_DB:-iptvapp}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-iptv}:${POSTGRES_PASSWORD:-iptv}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-iptvapp}
      JWT_SECRET: ${JWT_SECRET:-supersecret_change_me}
      TMDB_API_KEY: ${TMDB_API_KEY:-d8175301037c00f3c719478998396539}
      API_PORT: ${API_PORT:-4000}
      NODE_ENV: development
    ports:
      - "4000:4000"
  web:
    build: ./web
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:4000}
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  db_data:
