version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: nova
      POSTGRES_PASSWORD: nova
      POSTGRES_DB: nova
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Build l'image de l'app depuis le repo Git
  web:
    build: .
    ports:
      - "3000:3000"
    # On passe les variables via l'UI Portainer (Stack > Env), pas via .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_ACCESS_TTL_SECONDS=${JWT_ACCESS_TTL_SECONDS}
      - JWT_REFRESH_TTL_SECONDS=${JWT_REFRESH_TTL_SECONDS}
      - NOVA_CRYPT_KEY_BASE64=${NOVA_CRYPT_KEY_BASE64}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    depends_on:
      - db
    restart: unless-stopped

  # Job one-shot pour exécuter les migrations Prisma à chaque déploiement
  migrate:
    build: .
    command: ["npx", "prisma", "migrate", "deploy"]
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    restart: "no"

volumes:
  pgdata:
