version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: iptv
      POSTGRES_PASSWORD: iptv
      POSTGRES_DB: iptvapp
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - appnet

  api:
    build: ./backend
    environment:
      DATABASE_URL: postgres://iptv:iptv@db:5432/iptvapp
      JWT_SECRET: supersecret_change_me
      TMDB_API_KEY: "d8175301037c00f3c719478998396539"
      API_PORT: "4000"
      NODE_ENV: development
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped
    networks:
      - appnet
    # (déconseillé) exposer publiquement l'API :
    # ports:
    #   - "4000:4000"

  web:
  build:
    context: ./web
    args:
      VITE_API_URL: "/api"
      BUILD_ID: "cache-bust-8"   # ⬅️ incrémente ce nombre
    depends_on:
      api:
        condition: service_started
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge
