services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_ACCESS_TTL_SECONDS=${JWT_ACCESS_TTL_SECONDS}
      - JWT_REFRESH_TTL_SECONDS=${JWT_REFRESH_TTL_SECONDS}
      - NOVA_CRYPT_KEY_BASE64=${NOVA_CRYPT_KEY_BASE64}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    depends_on:
      - db
    restart: unless-stopped
