version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: novastream_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: novastream
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks: [novanet]
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    container_name: novastream_api
    depends_on: [db]
    env_file:
      - packages/api/.env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/novastream
      CORS_ORIGIN: http://localhost:3000
      REQUEST_TIMEOUT_MS: 20000
      DEFAULT_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120 Safari/537.36
    networks: [novanet]
    ports:
      - "4000:4000"

  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    container_name: novastream_web
    depends_on: [api]
    env_file:
      - packages/web/.env
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://api:4000
      NODE_ENV: production
    networks: [novanet]
    ports:
      - "3000:3000"

networks:
  novanet: {}
