version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: iptv-saas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: novastream
      POSTGRES_USER: novastream
      POSTGRES_PASSWORD: novastream
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novastream -d novastream"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: iptv-saas-redis
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    container_name: iptv-saas-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      NODE_ENV: production
      PORT: "3000"
      DATABASE_URL: postgresql://novastream:novastream@postgres:5432/novastream
      REDIS_URL: redis://redis:6379/0
      JWT_ACCESS_SECRET: "dev_access_secret_change_me"
      JWT_REFRESH_SECRET: "dev_refresh_secret_change_me"
      CORS_ORIGIN: "http://85.31.239.110:5173"
      TMDB_API_KEY: "d8175301037c00f3c719478998396539"
      # Commente ces 4 lignes si tu ne veux pas de MinIO:
      S3_ENDPOINT: "http://minio:9000"
      S3_BUCKET: "novastream"
      S3_ACCESS_KEY: "admin"
      S3_SECRET_KEY: "changeme123"
    ports:
      - "3000:3000"

  web:
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    container_name: iptv-saas-web
    restart: unless-stopped
    environment:
      VITE_API_BASE: "http://85.31.239.110:3000"
    depends_on:
      - api
    ports:
      - "5173:5173"

  # MinIO optionnel (commente si inutile)
  minio:
    image: quay.io/minio/minio:RELEASE.2024-07-26T20-48-21Z
    container_name: iptv-saas-minio
    restart: unless-stopped
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: changeme123
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 15s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
  minio-data:
