version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: iptv-saas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: novastream
      POSTGRES_USER: novastream
      POSTGRES_PASSWORD: novastream
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novastream -d novastream"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: iptv-saas-redis
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- API NestJS ---
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    container_name: iptv-saas-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      NODE_ENV: production
      PORT: "3000"
      # DB / Redis
      DATABASE_URL: postgresql://novastream:novastream@postgres:5432/novastream
      REDIS_URL: redis://redis:6379/0
      # Auth
      JWT_ACCESS_SECRET: "dev_access_secret_change_me"
      JWT_REFRESH_SECRET: "dev_refresh_secret_change_me"
      # CORS (mets ici l’URL d’accès au front)
      CORS_ORIGIN: "http://85.31.239.110:5173"
      # Enrichissement TMDB (optionnel mais recommandé)
      TMDB_API_KEY: "d8175301037c00f3c719478998396539"
      # S3/MinIO (optionnel — commente si non utilisé)
      S3_ENDPOINT: "http://minio:9000"
      S3_BUCKET: "novastream"
      S3_ACCESS_KEY: "admin"
      S3_SECRET_KEY: "changeme123"
    ports:
      - "3000:3000"

  # --- Front Web (Vite) ---
  web:
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    container_name: iptv-saas-web
    restart: unless-stopped
    environment:
      # Base API vue par le navigateur (mets l’IP/DNS public de ton serveur)
      VITE_API_BASE: "http://85.31.239.110:3000"
    depends_on:
      - api
    ports:
      - "5173:5173"

  # --- MinIO (stockage objets compatible S3) - OPTIONNEL ---
  minio:
    image: quay.io/minio/minio:RELEASE.2024-07-26T20-48-21Z
    container_name: iptv-saas-minio
    restart: unless-stopped
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: changeme123
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console Web
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 15s
      timeout: 5s
      retries: 10

  # --- Mock Xtream (pour tests) ---
  xtream-mock:
    build:
      context: ./packages/xtream-mock
      dockerfile: Dockerfile
    container_name: iptv-saas-xtream-mock
    restart: unless-stopped
    ports:
      - "8888:8080"

volumes:
  pgdata:
  minio-data:
