version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: iptv-saas-db
    environment:
      POSTGRES_USER: novastream
      POSTGRES_PASSWORD: novastream
      POSTGRES_DB: novastream
      TZ: Europe/Brussels
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novastream -d novastream"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: iptv-saas-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    container_name: iptv-saas-api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      NODE_ENV: production
      TZ: Europe/Brussels
      PORT: 3000

      # --- Auth / Cookies / CORS ---
      JWT_SECRET: "6#mVB0LwG26uQ8|tGyP:"     # ta clé
      COOKIE_SECURE: "false"                  # true si tu sers l’app en HTTPS
      CORS_ORIGIN: "http://85.31.239.110:5173"  # URL publique du front Vite

      # --- DB ---
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: novastream
      DB_PASS: novastream
      DB_NAME: novastream

      # --- TypeORM ---
      TYPEORM_SYNC: "true"  # dev/proto : synchronise le schéma automatiquement

      # --- Xtream (optionnel) ---
      # Passe à "true" si ton fournisseur bloque l'IP de ton serveur (WAF/403),
      # pour autoriser la liaison malgré un 403 et convertir en M3U.
      ALLOW_XTREAM_LINK_WITHOUT_VALIDATE: "false"
    ports:
      - "3000:3000"
    restart: unless-stopped

  web:
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    container_name: iptv-saas-web
    depends_on:
      - api
    environment:
      NODE_ENV: production
      TZ: Europe/Brussels
      # Très important : utilisé par le navigateur pour appeler l'API
      VITE_API_BASE: "http://85.31.239.110:3000"
    ports:
      - "5173:5173"
    restart: unless-stopped

volumes:
  db_data:
  redis_data:
