version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: iptv
      POSTGRES_PASSWORD: iptv
      POSTGRES_DB: iptvapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iptv -d iptvapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      args:
        API_BUILD_ID: "9"        # change ce nombre pour forcer un rebuild
    environment:
      DATABASE_URL: postgres://iptv:iptv@db:5432/iptvapp
      JWT_SECRET: supersecret_change_me
      TMDB_API_KEY: "d8175301037c00f3c719478998396539"
      API_PORT: "4000"
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    restart: unless-stopped

  web:
    build:
      context: ./web
      args:
        VITE_API_URL: "/api"     # le front appellera /api -> proxy nginx vers api
        BUILD_ID: "10"            # change pour casser le cache
    ports:
      - "8080:80"
    depends_on:
      api:
        condition: service_started
    restart: unless-stopped

volumes:
  db_data:
