services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: iptv
      POSTGRES_PASSWORD: iptv
      POSTGRES_DB: iptvapp
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks: [appnet]
    # (optionnel) exposer la DB en dehors du host :
    # ports:
    #   - "5432:5432"

  api:
    build: ./backend
    depends_on: [db]
    environment:
      DATABASE_URL: postgres://iptv:iptv@db:5432/iptvapp
      JWT_SECRET: supersecret_change_me
      TMDB_API_KEY: "d8175301037c00f3c719478998396539"
      API_PORT: "4000"
      NODE_ENV: development
    restart: unless-stopped
    networks: [appnet]
    # (déconseillé) exposer publiquement l'API :
    # ports:
    #   - "4000:4000"

  web:
    build:
      context: ./web
      args:
        # IMPORTANT : on fait pointer le front vers /api
        VITE_API_URL: "/api"
        # Change la valeur pour forcer un rebuild sans cache si besoin
        BUILD_ID: "cache-bust-1"
    depends_on: [api]
    ports:
      - "8080:80"
    restart: unless-stopped
    networks: [appnet]

volumes:
  db_data:

networks:
  appnet:
    driver: bridge
