services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: iptv
      POSTGRES_PASSWORD: iptv
      POSTGRES_DB: iptvapp
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet

  api:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://iptv:iptv@db:5432/iptvapp
      JWT_SECRET: supersecret_change_me
      TMDB_API_KEY: "d8175301037c00f3c719478998396539"
      API_PORT: "4000"
      NODE_ENV: development
    # on n'expose plus le port 4000 publiquement, on passe par le proxy nginx
    # ports:
    #   - "4000:4000"
    networks:
      - appnet

  web:
    build:
      context: ./web
      args:
        VITE_API_URL: "/api"   # IMPORTANT : chaîne => routes front -> /api/*
    depends_on:
      - api
    ports:
      - "8080:80"
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge
