services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: iptv
      POSTGRES_PASSWORD: iptv
      POSTGRES_DB: iptvapp
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://iptv:iptv@db:5432/iptvapp
      JWT_SECRET: supersecret_change_me
      TMDB_API_KEY: "d8175301037c00f3c719478998396539"
      API_PORT: "4000"
      NODE_ENV: development
    # (optionnel) tu peux commenter si tu ne veux plus exposer 4000 publiquement
    # ports:
    #   - "4000:4000"

  web:
    build:
      context: ./web
      args:
        VITE_API_URL: "/api"   # <— front appellera /api/*, Nginx proxy vers api:4000
    depends_on:
      - api
    ports:
      - "8080:80"

volumes:
  db_data:
