version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: novastream_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: novastream
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - novastream-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - novastream-net

  api:
    container_name: novastream_api
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    restart: unless-stopped
    env_file:
      - ./packages/api/.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - novastream-net

  web:
    container_name: novastream_web
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
    restart: unless-stopped
    env_file:
      - ./packages/web/.env
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - novastream-net

volumes:
  novastream-data:
    driver: local

networks:
  novastream-net:
    driver: bridge
